x-common:
  database:
    &db-environment
    MYSQL_PASSWORD: &db-password "<db_password>"
    MYSQL_ROOT_PASSWORD: "<db_root_password>"
  panel:
    &panel-environment
    APP_URL: "<app_url>"
    APP_DEBUG: "false"
    APP_TIMEZONE: "<timezone>"
    APP_SERVICE_AUTHOR: "<email>"
    LE_EMAIL: "<le_email>"
  mail:
    &mail-environment
    MAIL_FROM: "<email>"
    MAIL_DRIVER: "log"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

services:
  database:
    image: mariadb:12
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/opt/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    restart: always
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "/opt/pterodactyl/var/:/app/var/"
      - "/opt/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/opt/pterodactyl/certs/:/etc/letsencrypt/"
      - "/opt/pterodactyl/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
      HASHIDS_SALT: "<hashids_salt>"
      HASHIDS_LENGTH: 8

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
